In [5]:
# Loading Library
from stoneforge.data_management.preprocessing import DataLoader

In [6]:
# Manual Access:

las2 = DataLoader(r"https://raw.githubusercontent.com/giecaruff/datasets/refs/heads/main/wells/las2/massape/7-MP-56D-BA.las", filetype='las2') 
print('header itens:',las2.data_obj.header.keys())
las2.data_obj.header['well']

header itens: dict_keys(['version', 'well', 'curve'])

   mnemonic unit              value                      description
0      STRT    M          1868.0001                      START DEPTH
1      STOP    M          3172.9001                       STOP DEPTH
2      STEP    M             0.1000                       STEP VALUE
3      NULL               -999.0000                       NULL VALUE
4      DATE              22/09/2026           LAS file Creation Date
5      WELL             7-MP-56D-BA                        Well Name
6      COMP               PETROBRAS                          Company
7       FLD                 MASSAPE                            Field
8     STATE                   BAHIA                            State
9       API             20240028489                       API Number
10      UWI                             Unique Well Identifier (UWI)
11      LOC                                                 Location
12     TOWN                 -999.25                         Township
13      SCT                 -999.25                          Section
14     RANG                 -999.25                            Range
15     PDAT                      NM                  Permanent Datum
16    EPDAT                     0.0     Elevation of Permanent Datum
17    LGMEA                      MR                Log Measured from
18    DRMEA                      MR              Drill Measured From
19    APDAT                  100.38  Elevation Above Permanent Datum
20       KB                  100.68                     KB Elevation
21       DF                  100.38                     DF Elevation
22       GL                   90.98                     GL Elevation
23      RWS                    -999                           Def_Rw
24      WST                    -999                          Def_Rwt
25     PROV                                                 Province
26     SRVC                                               Contractor
27     GDAT                  WGS 84                         Geodatum
28     LONG       -38.4243922222985                        Longitude
29     LATI                       0                         Latitude
30  COORDIN                                              Grid System
31   XCOORD                                X or East-West Coordinate
32   YCOORD                              Y or North-South Coordinate

In [7]:
# View Raw Data
print(las2.data_obj.data)

{'DEPTH': {'values': array([1868.0001, 1868.1001, 1868.2001, ..., 3172.7001, 3172.8001,
       3172.9001], shape=(13050,)), 'unit': 'M', 'description': '7-mp-56d-ba_raw-1-6949.dlis'}, 'BS': {'values': array([8.5, 8.5, 8.5, ..., 8.5, 8.5, 8.5], shape=(13050,)), 'unit': 'in', 'description': '7-mp-56d-ba_raw-1-6949.dlis'}, 'GR': {'values': array([96.014 , 96.2027, 97.7789, ..., 89.598 , 91.4339,     nan],
      shape=(13050,)), 'unit': 'gapi', 'description': '7-mp-56d-ba_raw-1-6949.dlis'}, 'CALI': {'values': array([9.647 , 9.5881, 9.5809, ..., 7.2113, 7.2124, 7.2118],
      shape=(13050,)), 'unit': 'in', 'description': '7-mp-56d-ba_raw-1-6949.dlis'}, 'DT': {'values': array([91.3812, 91.0722, 90.1369, ..., 65.9171, 66.3742, 66.8357],
      shape=(13050,)), 'unit': 'uspf', 'description': '7-mp-56d-ba_raw-1-6949.dlis'}, 'RT30': {'values': array([ 2.4726,  2.4536,  2.4079, ..., 12.3821, 12.7422, 13.0314],
      shape=(13050,)), 'unit': 'ohmm', 'description': '7-mp-56d-ba_raw-1-6949.dlis'}, 'RT60': {'values': array([ 2.43  ,  2.4127,  2.3687, ..., 12.1954, 12.4908, 12.7365],
      shape=(13050,)), 'unit': 'ohmm', 'description': '7-mp-56d-ba_raw-1-6949.dlis'}, 'RT90': {'values': array([ 2.4973,  2.4801,  2.4348, ..., 11.9688, 12.2348, 12.4612],
      shape=(13050,)), 'unit': 'ohmm', 'description': '7-mp-56d-ba_raw-1-6949.dlis'}, 'RHOB': {'values': array([   nan, 2.4487, 2.4563, ..., 2.3339, 2.3376, 2.3386],
      shape=(13050,)), 'unit': 'g/cc', 'description': '7-mp-56d-ba_raw-1-6949.dlis'}, 'DRHO': {'values': array([   nan, 0.1205, 0.0974, ..., 0.1109, 0.116 , 0.1178],
      shape=(13050,)), 'unit': 'g/cc', 'description': '7-mp-56d-ba_raw-1-6949.dlis'}, 'NPHI': {'values': array([   nan, 0.2884, 0.283 , ..., 0.1504, 0.1495, 0.1494],
      shape=(13050,)), 'unit': 'decp', 'description': '7-mp-56d-ba_raw-1-6949.dlis'}}

In [8]:
# Example (Manual Access): Accessing data as DataFrame
data_las2, units_las2 = las2.dataframe(las2.data_obj.data)
data_las2

,DEPTH,BS,GR,CALI,DT,RT30,RT60,RT90,RHOB,DRHO,NPHI
0,1868.0001,8.5,96.0140,9.6470,91.3812,2.4726,2.4300,2.4973,NaN,NaN,NaN
1,1868.1001,8.5,96.2027,9.5881,91.0722,2.4536,2.4127,2.4801,2.4487,0.1205,0.2884
2,1868.2001,8.5,97.7789,9.5809,90.1369,2.4079,2.3687,2.4348,2.4563,0.0974,0.2830
3,1868.3001,8.5,98.0069,9.5892,89.3943,2.3368,2.3003,2.3639,2.4703,0.0721,0.2830
4,1868.4001,8.5,98.5336,9.4958,89.6868,2.1647,2.1346,2.1917,2.5003,0.0396,0.2731
...,...,...,...,...,...,...,...,...,...,...,...
13045,3172.5001,8.5,87.5305,7.2086,66.0265,12.3590,12.2146,12.0041,2.3356,0.1072,0.1468
13046,3172.6001,8.5,88.2076,7.2082,65.5312,12.3572,12.1929,11.9750,2.3341,0.1086,0.1477
13047,3172.7001,8.5,89.5980,7.2113,65.9171,12.3821,12.1954,11.9688,2.3339,0.1109,0.1504
13048,3172.8001,8.5,91.4339,7.2124,66.3742,12.7422,12.4908,12.2348,2.3376,0.1160,0.1495
13049,3172.9001,8.5,NaN,7.2118,66.8357,13.0314,12.7365,12.4612,2.3386,0.1178,0.1494