In [1]:
from stoneforge.data_management.preprocessing import DataLoader

In [2]:
# Update DLIS object with the path to your DLIS file

dlis_obj = DataLoader(r"7-mp-56d-ba_raw-1-6949.dlis", filetype = 'dlis')

In [3]:
# Data Access Preview

dlis_obj.data_obj.show_header()

   logical_file frame mnemonic  unit
0     GEOLOAD.1    50     TDEP     m
1     GEOLOAD.1    50     AHVT    m3
2     GEOLOAD.1    50     BHVT    m3
3     GEOLOAD.1    50       BS    in
4     GEOLOAD.1    50     CALI    in
5     GEOLOAD.1    50       DT  uspf
6     GEOLOAD.1    50     ITTT    ms
7     GEOLOAD.1    50     RT30  ohmm
8     GEOLOAD.1    50     RT60  ohmm
9     GEOLOAD.1    50     RT90  ohmm
10    GEOLOAD.1    50     CT90  mmo/
11    GEOLOAD.1    50     CT60  mmo/
12    GEOLOAD.1    50     CT30  mmo/
13    GEOLOAD.1    50     RHOB  g/cc
14    GEOLOAD.1    50     DRHO  g/cc
15    GEOLOAD.1    50     NPHI  decp
16    GEOLOAD.1    50     NDSN   cps
17    GEOLOAD.1    50     FDSN   cps
18    GEOLOAD.1    50     NRAT  NONE
19    GEOLOAD.1    50     UNPL  decp
20    GEOLOAD.1    50       GR  gapi
21    GEOLOAD.1    50     MINM
22    GEOLOAD.1    50       CS   mpm
23    GEOLOAD.1    50     TENS   lbs
24    GEOLOAD.2    50     TDEP     m
25    GEOLOAD.2    50     AHVT    m3
26    GEOLOAD.2    50     BHVT    m3
27    GEOLOAD.2    50       BS    in
28    GEOLOAD.2    50     CALI    in
29    GEOLOAD.2    50       DT  uspf
30    GEOLOAD.2    50     ITTT    ms
31    GEOLOAD.2    50     RT30  ohmm
32    GEOLOAD.2    50     RT60  ohmm
33    GEOLOAD.2    50     RT90  ohmm
34    GEOLOAD.2    50     CT90  mmo/
35    GEOLOAD.2    50     CT60  mmo/
36    GEOLOAD.2    50     CT30  mmo/
37    GEOLOAD.2    50     RHOB  g/cc
38    GEOLOAD.2    50     DRHO  g/cc
39    GEOLOAD.2    50     NPHI  decp
40    GEOLOAD.2    50     NDSN   cps
41    GEOLOAD.2    50     FDSN   cps
42    GEOLOAD.2    50     NRAT  NONE
43    GEOLOAD.2    50     UNPL  decp
44    GEOLOAD.2    50       GR  gapi
45    GEOLOAD.2    50     MINM
46    GEOLOAD.2    50       CS   mpm
47    GEOLOAD.2    50     TENS   lbs

In [4]:
# All mnemonics:

mns = dlis_obj.data_obj.mnemonics()
print(mns)

['AHVT', 'BHVT', 'BS', 'CALI', 'CS', 'CT30', 'CT60', 'CT90', 'DRHO', 'DT', 'FDSN', 'GR', 'ITTT', 'MINM', 'NDSN', 'NPHI', 'NRAT', 'RHOB', 'RT30', 'RT60', 'RT90', 'TDEP', 'TENS', 'UNPL']

In [5]:
# Import and display data structure

data = dlis_obj.data_obj.extract(mnemonics=mns)
for d in data:
    print("digital files:",d, "| frames:",data[d].keys())

digital files: GEOLOAD.1 | frames: dict_keys(['50'])
digital files: GEOLOAD.2 | frames: dict_keys(['50'])

In [6]:
# Access data for a specific frame and channel

data_dlis, units_dlis = dlis_obj.dataframe(data['GEOLOAD.1']['50'])
data_dlis.dropna()

,TDEP,AHVT,BHVT,BS,CALI,DT,ITTT,RT30,RT60,RT90,...,DRHO,NPHI,NDSN,FDSN,NRAT,UNPL,GR,MINM,CS,TENS
203,3172.800097,0.009800,0.163000,8.5,7.2124,66.374199,2.595900,12.7422,12.4908,12.2348,...,0.1160,0.1495,21654.287109,3037.261963,7.7180,0.1528,91.433899,0.0,6.5,7322.280762
204,3172.700097,0.010000,0.167000,8.5,7.2113,65.917099,2.628900,12.3821,12.1954,11.9688,...,0.1109,0.1504,21712.380859,2942.857178,7.7514,0.1538,89.598000,0.0,6.8,7289.094727
205,3172.600097,0.010100,0.169000,8.5,7.2082,65.531197,2.645200,12.3572,12.1929,11.9750,...,0.1086,0.1477,21817.142578,3077.142578,7.6613,0.1512,88.207603,0.0,6.7,7288.378906
206,3172.500097,0.010200,0.171000,8.5,7.2086,66.026497,2.661400,12.3590,12.2146,12.0041,...,0.1072,0.1468,21623.810547,3068.571289,7.6380,0.1506,87.530502,0.0,6.9,7331.180664
207,3172.400097,0.010500,0.175000,8.5,7.2069,67.541603,2.694700,12.3218,12.1950,11.9927,...,0.1065,0.1469,21788.095703,3082.857178,7.6531,0.1510,88.191498,0.0,7.0,7324.443848
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13246,1868.500078,16.438400,48.983700,8.5,9.4718,90.642197,339.340912,2.0933,2.0659,2.1202,...,0.0388,0.2752,18324.443359,1539.444336,12.9814,0.3105,97.350403,0.0,8.4,4616.217773
13247,1868.400078,16.440001,48.987202,8.5,9.4958,89.686798,339.363190,2.1647,2.1346,2.1917,...,0.0396,0.2731,18207.779297,1525.555542,12.9219,0.3086,98.533600,0.0,8.7,4558.872070
13248,1868.300078,16.443300,48.994202,8.5,9.5892,89.394302,339.407501,2.3368,2.3003,2.3639,...,0.0721,0.2830,18231.111328,1532.777710,13.2705,0.3196,98.006897,0.0,8.5,4543.774902
13249,1868.200078,16.444901,48.997700,8.5,9.5809,90.136902,339.429993,2.4079,2.3687,2.4348,...,0.0974,0.2830,17577.220703,1423.888794,13.2804,0.3200,97.778900,0.0,8.5,4544.893555
13250,1868.100078,16.446600,49.001301,8.5,9.5881,91.072197,339.452911,2.4536,2.4127,2.4801,...,0.1205,0.2884,17609.443359,1390.555542,13.4655,0.3259,96.202698,0.0,8.4,4525.071777

In [7]:
novo_df = data_dlis[(data_dlis['TDEP'] >= 1868) & (data_dlis['TDEP'] < 3173)]
novo_df

,TDEP,AHVT,BHVT,BS,CALI,DT,ITTT,RT30,RT60,RT90,...,DRHO,NPHI,NDSN,FDSN,NRAT,UNPL,GR,MINM,CS,TENS
202,3172.900097,0.009700,0.161000,8.5,7.2118,66.835701,2.579300,13.0314,12.7365,12.4612,...,0.1178,0.1494,21793.333984,3038.095459,7.7159,0.1528,NaN,0.0,6.7,7284.742676
203,3172.800097,0.009800,0.163000,8.5,7.2124,66.374199,2.595900,12.7422,12.4908,12.2348,...,0.1160,0.1495,21654.287109,3037.261963,7.7180,0.1528,91.433899,0.0,6.5,7322.280762
204,3172.700097,0.010000,0.167000,8.5,7.2113,65.917099,2.628900,12.3821,12.1954,11.9688,...,0.1109,0.1504,21712.380859,2942.857178,7.7514,0.1538,89.598000,0.0,6.8,7289.094727
205,3172.600097,0.010100,0.169000,8.5,7.2082,65.531197,2.645200,12.3572,12.1929,11.9750,...,0.1086,0.1477,21817.142578,3077.142578,7.6613,0.1512,88.207603,0.0,6.7,7288.378906
206,3172.500097,0.010200,0.171000,8.5,7.2086,66.026497,2.661400,12.3590,12.2146,12.0041,...,0.1072,0.1468,21623.810547,3068.571289,7.6380,0.1506,87.530502,0.0,6.9,7331.180664
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13247,1868.400078,16.440001,48.987202,8.5,9.4958,89.686798,339.363190,2.1647,2.1346,2.1917,...,0.0396,0.2731,18207.779297,1525.555542,12.9219,0.3086,98.533600,0.0,8.7,4558.872070
13248,1868.300078,16.443300,48.994202,8.5,9.5892,89.394302,339.407501,2.3368,2.3003,2.3639,...,0.0721,0.2830,18231.111328,1532.777710,13.2705,0.3196,98.006897,0.0,8.5,4543.774902
13249,1868.200078,16.444901,48.997700,8.5,9.5809,90.136902,339.429993,2.4079,2.3687,2.4348,...,0.0974,0.2830,17577.220703,1423.888794,13.2804,0.3200,97.778900,0.0,8.5,4544.893555
13250,1868.100078,16.446600,49.001301,8.5,9.5881,91.072197,339.452911,2.4536,2.4127,2.4801,...,0.1205,0.2884,17609.443359,1390.555542,13.4655,0.3259,96.202698,0.0,8.4,4525.071777
13251,1868.000078,16.449900,49.008400,8.5,9.6470,91.381203,339.498993,2.4726,2.4300,2.4973,...,NaN,NaN,NaN,NaN,NaN,NaN,96.014000,0.0,8.7,4495.496094