In [1]:
from stoneforge.data_management.preprocessing import DataLoader

In [2]:
# Update DLIS object with the path to your DLIS file

dlis_obj = DataLoader(r"DSDP_leg_96_hole_616_96_processed_data.dlis", filetype = 'dlis')

In [3]:
# Data Access Preview

dlis_obj.data_obj.show_header()

         logical_file   frame mnemonic   unit
0     FDC/CNL/GR_main  B59067     TDEP      m
1     FDC/CNL/GR_main  B59067      RGR   gAPI
2     FDC/CNL/GR_main  B59067     RHGX  g/cm3
3     FDC/CNL/GR_main  B59067     RHOB  g/cm3
4     FDC/CNL/GR_main  B59067     RNFD    1/s
5     FDC/CNL/GR_main  B59067     RNRA
6     FDC/CNL/GR_main  B59067     TENS    lbf
7     FDC/CNL/GR_main  B59067     TIME      s
8     FDC/CNL/GR_main  B59067       GR   gAPI
9     FDC/CNL/GR_main  B59067     CALI     in
10    FDC/CNL/GR_main  B59067       CS    m/h
11    FDC/CNL/GR_main  B59067     DIFF      m
12    FDC/CNL/GR_main  B59067     DPHI      %
13    FDC/CNL/GR_main  B59067     DRHO  g/cm3
14    FDC/CNL/GR_main  B59067     FCNL    1/s
15    FDC/CNL/GR_main  B59067     FFDC    1/s
16    FDC/CNL/GR_main  B59067     MARK      m
17    FDC/CNL/GR_main  B59067     NCNL    1/s
18    FDC/CNL/GR_main  B59067     NFDC    1/s
19    FDC/CNL/GR_main  B59067     NPHI      %
20    FDC/CNL/GR_main  B59067     NRAT
21    FDC/CNL/GR_main  B59067     RCAL     in
22    FDC/CNL/GR_main  B59067     RFFD    1/s
23  FDC/CNL/GR_repeat  B59180     TDEP      m
24  FDC/CNL/GR_repeat  B59180      RGR   gAPI
25  FDC/CNL/GR_repeat  B59180     RHGX  g/cm3
26  FDC/CNL/GR_repeat  B59180     RHOB  g/cm3
27  FDC/CNL/GR_repeat  B59180     RNFD    1/s
28  FDC/CNL/GR_repeat  B59180     RNRA
29  FDC/CNL/GR_repeat  B59180     TENS    lbf
30  FDC/CNL/GR_repeat  B59180     TIME      s
31  FDC/CNL/GR_repeat  B59180       GR   gAPI
32  FDC/CNL/GR_repeat  B59180     CALI     in
33  FDC/CNL/GR_repeat  B59180       CS    m/h
34  FDC/CNL/GR_repeat  B59180     DIFF      m
35  FDC/CNL/GR_repeat  B59180     DPHI      %
36  FDC/CNL/GR_repeat  B59180     DRHO  g/cm3
37  FDC/CNL/GR_repeat  B59180     FCNL    1/s
38  FDC/CNL/GR_repeat  B59180     FFDC    1/s
39  FDC/CNL/GR_repeat  B59180     MARK      m
40  FDC/CNL/GR_repeat  B59180     NCNL    1/s
41  FDC/CNL/GR_repeat  B59180     NFDC    1/s
42  FDC/CNL/GR_repeat  B59180     NPHI      %
43  FDC/CNL/GR_repeat  B59180     NRAT
44  FDC/CNL/GR_repeat  B59180     RCAL     in
45  FDC/CNL/GR_repeat  B59180     RFFD    1/s

In [4]:
# All mnemonics:

mns = dlis_obj.data_obj.mnemonics()
print(mns)

['CALI', 'CS', 'DIFF', 'DPHI', 'DRHO', 'FCNL', 'FFDC', 'GR', 'MARK', 'NCNL', 'NFDC', 'NPHI', 'NRAT', 'RCAL', 'RFFD', 'RGR', 'RHGX', 'RHOB', 'RNFD', 'RNRA', 'TDEP', 'TENS', 'TIME']

In [5]:
# Import and display data structure

data = dlis_obj.data_obj.extract(mnemonics=mns)
for d in data:
    print("digital files:",d, "| frames:",data[d].keys())

digital files: FDC/CNL/GR_main | frames: dict_keys(['B59067'])
digital files: FDC/CNL/GR_repeat | frames: dict_keys(['B59180'])

In [6]:
# Access data for a specific frame and channel

data_dlis, units_dlis = dlis_obj.dataframe(data['FDC/CNL/GR_main']['B59067'])
data_dlis

,TDEP,RGR,RHGX,RHOB,RNFD,RNRA,TENS,TIME,GR,CALI,...,DRHO,FCNL,FFDC,MARK,NCNL,NFDC,NPHI,NRAT,RCAL,RFFD
0,372.465607,72.937500,3.330078,2.089844,1501.0,4.457031,-5.0,0.799000,133.250000,7.855561,...,0.047852,240.2500,1249.0,0.0,1071.0,810.00,61.279297,4.433594,7.859375,1862.0
1,372.313202,72.937500,3.330078,2.089844,1501.0,4.457031,-0.0,18.271999,133.250000,7.855561,...,0.047852,240.2500,1249.0,0.0,1071.0,810.00,61.279297,4.433594,7.859375,1862.0
2,372.160797,72.937500,3.330078,2.089844,1501.0,4.457031,5.0,1.159000,133.250000,7.855561,...,0.047852,240.2500,1249.0,0.0,1071.0,810.00,61.279297,4.433594,7.859375,1862.0
3,372.008392,72.937500,3.330078,2.089844,1501.0,4.457031,-5.0,1.001000,133.250000,7.855561,...,0.047852,240.2500,1249.0,0.0,1071.0,810.00,61.279297,4.433594,7.859375,1862.0
4,371.856018,72.937500,3.330078,2.089844,1501.0,4.457031,-5.0,0.832000,133.250000,7.855561,...,0.047852,240.2500,1249.0,0.0,1071.0,810.00,61.279297,4.433594,7.859375,1862.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2469,-3.809856,4.414062,2.736328,1.119141,843.5,7.871094,-0.0,0.731000,6.449219,7.917077,...,-0.422363,81.9375,4284.0,0.0,645.0,461.00,98.828125,6.523438,7.921875,6372.0
2470,-3.962256,3.533203,2.750000,1.106445,839.0,5.996094,-5.0,0.730000,5.375000,7.917077,...,-0.438477,102.5625,4248.0,0.0,615.0,450.25,108.496094,7.062500,7.917969,6340.0
2471,-4.114656,0.883301,2.728516,1.120117,819.5,7.437500,-5.0,0.727000,3.765625,7.898622,...,-0.425781,92.1875,4240.0,0.0,686.0,457.50,96.728516,6.410156,7.902344,6284.0
2472,-4.267056,1.768555,2.748047,1.113281,884.5,5.894531,-5.0,0.722000,3.751953,7.923228,...,-0.434082,102.6875,4224.0,0.0,605.5,451.75,106.640625,6.960938,7.925781,6328.0
2473,-4.419456,3.511719,2.734375,1.109375,807.5,7.664062,-5.0,0.721000,3.753906,7.898622,...,-0.437012,92.7500,4228.0,0.0,711.0,450.50,99.316406,6.550781,7.902344,6268.0